config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
  resources :users
  get 'vocab_lists/game/:id' => 'vocab_lists#game', as: 'game'
  resources :vocab_lists
  get '/words/popular' => 'words#popular'
  resources :words
  get '/test' => 'vocab_lists#test'
  root to: 'users#show'
end

app/models/class vocab_list.rb
class VocabList < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :omniauthable, :omniauth_providers => [:facebook]

  # has_and_belongs_to_many :vocab_lists
  has_many :vocab_lists

  def self.find_for_facebook_oauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.image = auth.info.image # assuming the user model has an image
    end
  end


end

app/models/vocab_list.rb
class VocabList < ActiveRecord::Base
  has_and_belongs_to_many :words
  # has_and_belongs_to_many :users
  # belongs_to :list_owner, class_name: 'User'
  belongs_to :user

end

app/models/word.rb
class Word < ActiveRecord::Base
  has_and_belongs_to_many :vocab_lists

  WORDNIK_API_PREFIX = 'http://api.wordnik.com:80/v4/word.json/'
  WORDNIK_API_SUFFIX = '/definitions?limit=20&includeRelated=true&sourceDictionaries=wiktionary&useCanonical=true&includeTags=false&api_key='

  def dictionary_lookup
    result = HTTParty.get(WORDNIK_API_PREFIX + self.word_name + WORDNIK_API_SUFFIX + ENV['WORDNIK_API_KEY'])
    if result.first == nil
      return false
    else
      self.part_of_speech = result.first["partOfSpeech"]
      self.definition = result.first["text"]
      return "successful"
    end
  end

  def update_list_count
    self.list_count = self.vocab_lists.length
    self.save!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index

  end

  def show
    @user = current_user
  end

end

app/controllers/vocab_lists_controller.rb
class VocabListsController < ApplicationController

  def index
    @vocab_lists = VocabList.all
  end

  def show
    @vocab_list = VocabList.find(params[:id])
  end

  def new
    @vocab_list = VocabList.new
  end

  def create
    @vocab_list = VocabList.new(vocab_params)
    @vocab_list.user = current_user
    # @vocab_list.users.push(current_user)
    # @vocab_list.list_owner = current_user
    @vocab_list.save!
    redirect_to current_user
  end

  def edit
    @vocab_list = VocabList.find(params[:id])
  end

  def update
    @vocab_list = VocabList.find(params[:id])
    @vocab_list.update(vocab_params)
  end

  def destroy
    @vocab_list = VocabList.find(params[:id])
  end

  def test

  end

  def game
    @vocab_list = VocabList.find(params[:id])
  end

  private
  def vocab_params
    params.require(:vocab_list).permit(:list_name)
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def index
    @words = Word.order("list_count desc")
  end

  def show

  end

  def new
    @word = Word.new
    if params[:word_name] != nil
      @chosen_word_name = params[:word_name]
    end
  end

  def create
    @word = Word.find_or_create_by(word_name: word_params[:word_name].downcase)
    @list = VocabList.find(word_params[:vocab_lists].to_i)
    if @list.words.include? @word
      flash[:notice] = "That word is already in this list."
    else
      @word.vocab_lists.push(@list)
      lookup = @word.dictionary_lookup
      if lookup == 'successful'
        @word.update_list_count
        flash[:alert] = nil
        redirect_to @list
      else
        @word.destroy!
        flash[:alert] = "Try again. You misspelled the word."
        render :new
      end
    end
  end

  def popular
    @words = Word.order("list_count desc").limit(10)
  end

  private
  def word_params
    params.require(:word).permit(:word_name, :vocab_lists)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>VocabApp</title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Vocab_App</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#">Right Button Active</a></li>
      <li class="has-dropdown">
        <a href="#">Menu</a>
        <ul class="dropdown">
          <li><a href="#">First link in dropdown</a></li>
        </ul>
      </li>
    </ul>

  </section>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if user_signed_in? %>
  <%= yield %>
<% else %>
  <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
<% end %>
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/users/show.html.erb
<div class="row">
  <div class="small-4">
    <p>Welcome <%= current_user.first_name %> |
    <%= link_to "Sign Out", destroy_user_session_path, method: 'delete' %></p>
  </div>
</div>

<div class="row">
  <div class="small-10 small-offset-1">
    <h3><%= current_user.first_name %>'s Vocab Lists</h3>
    <hr>
    <% current_user.vocab_lists.all.each do |list| %>
    <p><%= link_to list.list_name, vocab_list_path(list) %> (<%= list.words.length %> words)</p>
    <% end %>
    <%= link_to "Create a New Vocab List", new_vocab_list_path %>
  </div>
</div>
<br>

app/views/vocab_lists/_form.html.erb
<%= form_for @vocab_list do |f| %>
  <%= f.label :list_name %>
  <%= f.text_field :list_name %>

  <%= f.submit :submit %>
<% end %>

app/views/vocab_lists/game.html.erb
<div class="row">
  <div class="small-6 columns">
    <h3>Learn Yo' Words!</h3>
  </div>
</div>

<div class="row">
  <div class="small-10 small-offset-1 columns">
    <div class="flip">
      <div class="card">
        <div class="face front">
          <h4 class="front-word-title"></h4>
        </div> <!-- END FACE FRONT -->

        <div class="face back">
          <h6 class="def-word-title">
            <hr class="definition">
            <p class="definition" id="part-of-speech"></p>
            <p class="definition" id="definition"></p>
          </h6> <!-- END DEF-WORD-TITLE -->
        </div> <!-- END FACE BACK -->

      </div> <!-- END CARD -->
    </div> <!-- END FLIP -->
  </div>
</div>

app/views/vocab_lists/new.html.erb
<%= render 'form' %>

app/views/vocab_lists/show.html.erb
<script src="vocab_show.js"></script>

<div class="row">
  <div class="small-10 small-centered columns">
    <h1><%= @vocab_list.list_name %></h1>
    <hr>
  </div>
</div>

<div class="row">
  <div class="small-10 small-offset-1 columns">
    <% if @vocab_list.words == [] %>
      <p>There are no words yet in this list. <%= link_to 'Add some', new_word_path %>?</p>
    <% else %>
      <p><%= link_to 'Add more words!', new_word_path %></p>
      <p><%= link_to 'Play the Flashcard Game!', game_path(@vocab_list) %></p>
      <% @vocab_list.words.order("word_name asc").each do |word| %>
        <%= content_tag(:div, class: "flip", id: dom_id(word), data: { word_info: word } ) do -%>
        <div class="card">
          <div class="face front">
            <h4 class="front-word-title"><%= word.word_name.upcase %></h4>
          </div>

          <div class="face back">
            <h6 class="def-word-title"><%= word.word_name.upcase %></h6>
            <hr class="definition">
            <p class="definition"><b>part of speech:</b> <%= word.part_of_speech %></p>
            <p class="definition"><b>definition:</b> <%= word.definition %></p>
          <% end -%>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/vocab_lists/test.html.erb
<div id="js-flip-1" class="flip">
    <div class="card">
        <div class="face front">Front</div>
        <div class="face back">Back</div>
    </div>
</div>

app/views/words/_form.html.erb
<%= form_for @word do |f| %>
  <%= f.label :word_name %>
  <%= f.text_field :word_name, id: 'input' %>

  <%= f.label :vocab_list %>
  <%= f.select(:vocab_lists, options_from_collection_for_select(VocabList.all, :id, :list_name)) %>

  <%= f.submit :submit %>
<% end %>

app/views/words/index.html.erb
<h1>Most Popular Saved Words</h1>

<% @words.each do |word| %>
  <ul>
  <li><%= word.word_name.capitalize %></li>
  <li>This word has been saved <%= word.list_count %> <%= word.list_count > 1 ? "times" : "time" %>.</li>
  </ul>
<% end %>

app/views/words/new.html.erb
<script src="popular.js"></script>
<% if @chosen_word_name %>
  <p class="hide" id="chosen-word-name"><%= @chosen_word_name %></p>
<% end %>
<div class="row">
  <div class="small-6 small-centered columns">
    <h4>Add a Word</h4>
      <hr>
        <br>
          <%= render 'form' %>
        <br>
      <hr>
    <a href="<%= words_popular_path %>"><h6>View Most Popular Words</h6></a>
  </div>
</div>

app/views/words/popular.html.erb
<div class="row">
  <div class="small-10 columns">
    <h4>These are the most popular words on the site.</h4>
  </div>
  <hr>
</div>
<br>
<div class="row">
  <div class="small-10 columns">
    <% @words.each do |word| %>
      <ul>
        <li><%= word.word_name %> - (saved <%= word.list_count %> times) <%= link_to '[add]', new_word_path(:word_name => word.word_name) %></li>
      </ul>
    <% end %>
  </div>
</div>